# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='comment',
        ),
        migrations.AddField(
            model_name='word',
            name='freeTrans2Example',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='word',
            name='freeTransExample',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='word',
            name='wordExample',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='freeTrans',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='freeTrans2',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
